CREATE DATABASE DVR;
USE DVR;

CREATE TABLE MEMBER (
	id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	regDate DATETIME,
	updateDate DATETIME,
	delDate DATETIME,
	delStatus TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	authStatus TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	loginId CHAR(20) NOT NULL UNIQUE,
	loginPw CHAR(100) NOT NULL,
	`name` CHAR(20) NOT NULL,
	`nickname` CHAR(20) NOT NULL,
	`email` CHAR(100) NOT NULL,
	phoneNo CHAR(20) NOT NULL
);